# Generated by Django on 2026-04-09

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import foodguardapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="last login",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", foodguardapp.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="FoodAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="food_images/%Y/%m/%d/")),
                ("user_note", models.TextField(blank=True)),
                ("food_name_detected", models.CharField(max_length=200)),
                (
                    "safety_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "safety_verdict",
                    models.CharField(
                        choices=[("Safe", "Safe"), ("Caution", "Caution"), ("Avoid", "Avoid")],
                        max_length=10,
                    ),
                ),
                ("analysis_json", models.JSONField(default=dict)),
                ("is_halal_flagged", models.BooleanField(default=False)),
                ("is_allergen_flagged", models.BooleanField(default=False)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                        max_length=20,
                    ),
                ),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("height_cm", models.FloatField(blank=True, null=True)),
                ("area_in_dhaka", models.CharField(blank=True, max_length=100)),
                ("health_conditions", models.JSONField(blank=True, default=list)),
                ("allergies", models.JSONField(blank=True, default=list)),
                (
                    "dietary_restrictions",
                    models.CharField(
                        choices=[
                            ("Halal Only", "Halal Only"),
                            ("Vegetarian", "Vegetarian"),
                            ("Vegan", "Vegan"),
                            ("No Restriction", "No Restriction"),
                        ],
                        default="Halal Only",
                        max_length=30,
                    ),
                ),
                (
                    "fitness_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lose Weight", "Lose Weight"),
                            ("Gain Muscle", "Gain Muscle"),
                            ("Maintain", "Maintain"),
                            ("Manage Condition", "Manage Condition"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sedentary", "Sedentary"),
                            ("Light", "Light"),
                            ("Moderate", "Moderate"),
                            ("Active", "Active"),
                        ],
                        max_length=20,
                    ),
                ),
                ("profile_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
